### ISSUE TITLE
Noetic port of ```robotnik_base_hw_lib```?

### ISSUE THREAD

**Issue by Mechazo11** [RobotnikAutomation/robotnik_base_hw#14]
Hello @RomanRobotnik,

We have two RBKAIROS units in the iCORE Lab at Louisiana State University. We are working on a large scale project and need to bring all systems (summit_xl, 3d reconstruction, etc) components into ROS Noetic.

We have gotten quite far but have recently faced an issue compiling the ```robotnik_base_hw``` package. It appears to have a dependency on the ```robotnik_base_hw_lib``` that had an update last year but was still meant for Melodic.

Is there a Noetic version of this ```.deb``` file? If not, what may be the general procedure to fix the dependency issues and convert it back to a ```.deb``` suitable for ROS Noetic?

Thank you for your time.

With best regards,
@Mechazo11

**Comment by RomanRobotnik** [comment]
Hi @Mechazo11,

Sure, my colleague @robert-ros will provide everything you need.

Best regards,

Román

**Comment by Mechazo11** [comment]
@RomanRobotnik thank you very much for connecting me with @robert-ros 

Hi @robert-ros if you would kindly share the ```.deb``` file for ```robotnik_base_hw_lib``` I can go ahead and test it with the noetic port we are working on in our lab.

With best,
@Mechazo11

**Comment by jamendezib** [comment]
Hi @Mechazo11 

I have uploaded our latest ```.deb``` file to the ```lib``` folder in this branch: https://github.com/RobotnikAutomation/robotnik_base_hw/tree/fix/noetic_lib

**Comment by Mechazo11** [comment]
@jamendezib thank you very much. I will test it right away and report back if the issue gets resolved.

**Comment by Mechazo11** [comment]
@jamendezib 
Where can I find the ```ros-noetic-robotnik-msgs``` package? 

![Screenshot from 2024-05-16 10-45-52](https://github.com/RobotnikAutomation/robotnik_base_hw/assets/44814419/e9de6de3-f0a1-4f29-97eb-9c794dba0bf5)

**Comment by jamendezib** [comment]
@Mechazo11 I have updated the branch with robotnik_msgs deb

**Comment by Mechazo11** [comment]
@jamendezib thank you very much, I shall let you know if the issue gets resolved

**Comment by Mechazo11** [comment]
Hi @jamendezib  and @RomanRobotnik, ```robotnik_base_hw``` with the two .deb files provided for noetic, now builds successfully. 

I will report back if any further issues arises for the ```robotnik_base_hw``` package in Noetic. Thank you very much for promptly helping us resolve this issue.

**Comment by Mechazo11** [comment]
Hi @robert-ros,

Thank you very much for helping me with the build problem back in May. Presently I can build the entire ```catkin_ws``` in after carefully updating a number of packages to their Noetic version. But when trying to launch the various subsystems using ```./bringup.sh``` or ```roslaunch robot_bringup robot_complete.launch``` I am seeing this fatal run time error.

```
[ERROR] [1723151172.526408854]: RobotnikBaseHW::Constructor: Error while reading joint_inputs_per_driver parameter. I expect to read one value (for legacy behaviour) or as much as joints are there (2), but I have read 0.
[ERROR] [1723151172.526848132]: RobotnikBaseHW::Constructor: Error while reading joint_outputs_per_driver parameter. I expect to read one value (for legacy behaviour) or as much as joints are there (2), but I have read 0.
[ERROR] [1723151172.527284330]: RobotnikBaseHW::Constructor: Error while reading joint_analog_inputs_per_driver parameter. I expect to read one value (for legacy behaviour) or as much as joints are there (2), but I have read 0.
[ INFO] [1723151172.528547095]: RobotnikBaseHW::readParam: No multiple PID's params read!
[ WARN] [1723151172.537576167]: RobotnikBaseHW::Constructor: the param motors_encoder is DEPRECATED, please use directly the param joint_encoder_resolution.
[ WARN] [1723151172.537880063]: RobotnikBaseHW::Constructor: the param motors_encoder_factor is DEPRECATED, please use directly the param joint_encoder_resolution.

```

I have isolated the problem the point where ```robot_complete.launch``` attempts to launch nodes from ```robotnik_hw_base``` pkg using the following

```
<!-- start robotnik_base_hw node -->
    <include file="$(find robot_bringup)/launch/bringup/robotnik_base_hw.launch">
      <arg name="prefix" value="$(arg prefix)"/>
      <arg name="battery_voltage_offset" value="$(arg battery_voltage_offset)"/>
    </include>
```

Can you help me in solving this problem?
Best regards,
@Mechazo11

**Comment by Mechazo11** [comment]
Hello, 
To investigate further what the above error is I tried to launch ```robotnik_hw_base``` by itself. Shown below is the console output
```
robot@SXLSK-210223AB:~$ roslaunch robot_bringup robotnik_base_hw.launch 
... logging to /home/robot/.ros/log/ca92a650-5a7e-11ef-8d5c-93bd4df24cd5/roslaunch-SXLSK-210223AB-5962.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://SXLSK-210223AB:43533/

SUMMARY
========

PARAMETERS
 * /generic_hw_control_loop/cycle_time_error_threshold: 0.01
 * /generic_hw_control_loop/loop_hz: 300
 * /hardware_interface/joints: ['robot_front_rig...
 * /joint_limits/robot_back_left_wheel_joint/has_acceleration_limits: False
 * /joint_limits/robot_back_left_wheel_joint/has_effort_limits: False
 * /joint_limits/robot_back_left_wheel_joint/has_jerk_limits: False
 * /joint_limits/robot_back_left_wheel_joint/has_position_limits: False
 * /joint_limits/robot_back_left_wheel_joint/has_velocity_limits: True
 * /joint_limits/robot_back_left_wheel_joint/max_acceleration: 27.27
 * /joint_limits/robot_back_left_wheel_joint/max_velocity: 27.27
 * /joint_limits/robot_back_right_wheel_joint/has_acceleration_limits: False
 * /joint_limits/robot_back_right_wheel_joint/has_effort_limits: False
 * /joint_limits/robot_back_right_wheel_joint/has_jerk_limits: False
 * /joint_limits/robot_back_right_wheel_joint/has_position_limits: False
 * /joint_limits/robot_back_right_wheel_joint/has_velocity_limits: True
 * /joint_limits/robot_back_right_wheel_joint/max_acceleration: 27.27
 * /joint_limits/robot_back_right_wheel_joint/max_velocity: 27.27
 * /joint_limits/robot_front_left_wheel_joint/has_acceleration_limits: False
 * /joint_limits/robot_front_left_wheel_joint/has_effort_limits: False
 * /joint_limits/robot_front_left_wheel_joint/has_jerk_limits: False
 * /joint_limits/robot_front_left_wheel_joint/has_position_limits: False
 * /joint_limits/robot_front_left_wheel_joint/has_velocity_limits: True
 * /joint_limits/robot_front_left_wheel_joint/max_acceleration: 27.27
 * /joint_limits/robot_front_left_wheel_joint/max_velocity: 27.27
 * /joint_limits/robot_front_right_wheel_joint/has_acceleration_limits: False
 * /joint_limits/robot_front_right_wheel_joint/has_effort_limits: False
 * /joint_limits/robot_front_right_wheel_joint/has_jerk_limits: False
 * /joint_limits/robot_front_right_wheel_joint/has_position_limits: False
 * /joint_limits/robot_front_right_wheel_joint/has_velocity_limits: True
 * /joint_limits/robot_front_right_wheel_joint/max_acceleration: 27.27
 * /joint_limits/robot_front_right_wheel_joint/max_velocity: 27.27
 * /robotnik_base_hw/auto_restart: True
 * /robotnik_base_hw/calculate_vel_using_pose: True
 * /robotnik_base_hw/gearbox_ratio: 9.56
 * /robotnik_base_hw/joint_can_id: [1, 2, 3, 4]
 * /robotnik_base_hw/joint_home_offset: [0, 0, 0, 0]
 * /robotnik_base_hw/joint_name: ['robot_front_lef...
 * /robotnik_base_hw/joint_spin: [1, 1, -1, -1]
 * /robotnik_base_hw/joint_type: ['vel', 'vel', 'v...
 * /robotnik_base_hw/k_analog_inputs_multipliers: [16.61, -12.5, 1....
 * /robotnik_base_hw/k_battery_voltage_offset: 0.0
 * /robotnik_base_hw/motors_encoder: True
 * /robotnik_base_hw/motors_encoder_factor: 4000
 * /robotnik_base_hw/port: /dev/pcan_base
 * /robotnik_base_hw/recovery_period: 30
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    robotnik_base_hw (robotnik_base_hw/robotnik_base_hw_node)

auto-starting new master
process[master]: started with pid [5970]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ca92a650-5a7e-11ef-8d5c-93bd4df24cd5
process[rosout-1]: started with pid [5980]
started core service [/rosout]
process[robotnik_base_hw-2]: started with pid [5987]
[ INFO] [1723668609.115183887]: RobotnikBaseHW::Constructor: Port: /dev/pcan_base
[ERROR] [1723668609.120209900]: RobotnikBaseHW::Constructor: Error while reading joint_inputs_per_driver parameter. I expect to read one value (for legacy behaviour) or as much as joints are there (4), but I have read 0.
[ERROR] [1723668609.120503262]: RobotnikBaseHW::Constructor: Error while reading joint_outputs_per_driver parameter. I expect to read one value (for legacy behaviour) or as much as joints are there (4), but I have read 0.
[ERROR] [1723668609.120786201]: RobotnikBaseHW::Constructor: Error while reading joint_analog_inputs_per_driver parameter. I expect to read one value (for legacy behaviour) or as much as joints are there (4), but I have read 0.
[ INFO] [1723668609.122092292]: RobotnikBaseHW::readParam: No multiple PID's params read!
[ WARN] [1723668609.128970542]: RobotnikBaseHW::Constructor: the param motors_encoder is DEPRECATED, please use directly the param joint_encoder_resolution.
[ WARN] [1723668609.129200687]: RobotnikBaseHW::Constructor: the param motors_encoder_factor is DEPRECATED, please use directly the param joint_encoder_resolution.
[ INFO] [1723668609.135047263]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
[ INFO] [1723668609.237096779]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
[ INFO] [1723668609.340000455]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
[ INFO] [1723668609.442850362]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
[ INFO] [1723668609.545602606]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
[ INFO] [1723668609.648319958]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
^C[robotnik_base_hw-2] killing on exit
[ INFO] [1723668609.706190626]: RobotnikBaseHW::loadURDF: Waiting for model URDF on the ROS param server at location: /robot_description
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

I have traced the origin of the error from the binary files of ```robotnik_hardware_base_lib```. Can you help with this error?

With best regards,
@Mechazo11

**Comment by jamendezib** [comment]
Hi @Mechazo11,

Could you show me if possible the launch file `robotnik_base_hw.launch` and the `yaml` files that it is loading?

**Comment by Mechazo11** [comment]
Hi @jamendezib 

Following, in sequence, are the ```robotnik_base_hw.launch``` and the ```yaml``` files 

**robotnik_base_hw.launch**

```console
<?xml version="1.0"?>
<launch>
    <arg name="id_robot" default="$(optenv ROBOT_ID robot)"/>
    <arg name="prefix" default="$(arg id_robot)_"/>

    <!-- GDB functionality -->
    <arg name="debug" default="false" />
    <arg unless="$(arg debug)" name="launch_prefix" value="" />
    <arg     if="$(arg debug)" name="launch_prefix" value="terminator -m -x gdb --args" /> <!-- local debug -->
    <!--arg     if="$(arg debug)" name="launch_prefix" value="screen -d -m gdb - -args" / --> <!-- ssh/screen debug -->
    
    <!-- Values to multiply on IO raw data received -->
    <arg name="k_analog_inputs_multipliers" value="$(optenv ROBOT_K_ANALOG_INPUTS_MULTIPLIERS [1.0, 1.0, 1.0, 1.0])" />
    <arg name="robot_gearbox" default="$(optenv ROBOT_GEARBOX 12.52)"/>
    <arg name="has_encoder" default="$(optenv ROBOT_HAS_ENCODER false)"/>
    <arg name="battery_voltage_offset" default="$(optenv ROBOT_BASE_HW_BATTERY_VOLTAGE_OFFSET 0.0)"/>
   
    <rosparam file="$(find robot_bringup)/config/bringup/robotnik_base_hw/robotnik_base_hw_limits.yaml" command="load" subst_value="true"/>
    <rosparam file="$(find robot_bringup)/config/bringup/robotnik_base_hw/robotnik_base_hw.yaml" command="load" subst_value="true"/>

    <node name="robotnik_base_hw" pkg="robotnik_base_hw" type="robotnik_base_hw_node" output="screen" launch-prefix="$(arg launch_prefix)"/>
    
</launch>
```
**robotnik_base_hw_limits.yaml**

```yaml

joint_limits:
  $(arg prefix)front_left_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27   # 3 m/s = 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  $(arg prefix)front_right_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  $(arg prefix)back_left_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  $(arg prefix)back_right_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
```

**robotnik_base_hw.yaml**

```yaml

robotnik_base_hw:
  port: /dev/pcan_base
  
  # Auto-recovery behaviour when motors are in EMERGENCY and cannot recover by themselves
  auto_restart: true
  recovery_period: 30
  
  # Use encoder position instead of velocity for motor velocity calculation
  calculate_vel_using_pose: $(arg has_encoder)
  # 24V motors: 12.52, 48V motors: 9.56
  gearbox_ratio: $(arg robot_gearbox)
  # Be carefull if motors don't have enconders and you put motors_enconder: true speed will increase x 4000
  motors_encoder: $(arg has_encoder)
  motors_encoder_factor: 4000

  joint_name: [$(arg prefix)front_left_wheel_joint,$(arg prefix)back_left_wheel_joint,$(arg prefix)front_right_wheel_joint,$(arg prefix)back_right_wheel_joint]
  joint_can_id: [1,2,3,4]
  joint_type: [vel,vel,vel,vel]
  joint_home_offset: [0,0,0,0]
  joint_spin: [1,1,-1,-1]

  # Values to multiply on IO raw data received
  k_analog_inputs_multipliers: $(arg k_analog_inputs_multipliers)
  k_battery_voltage_offset: $(arg battery_voltage_offset)

generic_hw_control_loop:
  loop_hz: 300 
  cycle_time_error_threshold: 0.01


# Settings for ros_control hardware interface
hardware_interface:
  joints:
     - $(arg prefix)front_right_wheel_joint
     - $(arg prefix)front_left_wheel_joint
     - $(arg prefix)back_right_wheel_joint
     - $(arg prefix)back_left_wheel_joint
```

Please don't hesitate to reach out if you need further information. 

With best,
@Mechazo11
